apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digiabd.fullname" . }}-secrets
  labels:
    {{- include "digiabd.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  KEYCLOAK_ADMIN_USER: {{ .Values.secrets.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
  KEYCLOAK_DB_USER: {{ .Values.secrets.keycloakDbUser | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.secrets.keycloakDbPassword | quote }}
  KEYCLOAK_DB_NAME: {{ .Values.secrets.keycloakDbName | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
